export const uiText = {
  actions: {
    add: "Add",
    cancel: "Cancel",
    delete: "Delete",
    save: "Save",
  },
  hierarchy: {
    volume: "Volume",
    chapter: "Chapter",
    act: "Act",
    scene: "Scene",
  },
  library: {
    deleteNameLabel: "Type the project name to permanently delete it",
    deletePermanently: "Delete permanently",
    deleteProjectCopy: (title: string) => `This permanently deletes "${title}" from disk. This cannot be undone.`,
    deleteProjectTitle: "Permanently delete project?",
    firstVolume: "First volume",
    moveToTrash: "Move to Trash",
    open: "Open",
    opening: "Opening",
    projectLibrary: "Project Library",
    restore: "Restore",
    trash: "Trash",
    trashEmpty: "Trash is empty.",
    volumes: "volumes",
  },
  structure: {
    title: "Structure",
    createItem: "Create structure item",
    confirmDeletion: "Confirm structure deletion",
    deleteSelected: (label: string) => `Delete selected ${label}?`,
    doubleClickToRename: "Double-click to rename",
    emptyScene: "No scene",
  },
  errors: {
    cannotCreateChapterWithoutVolume: "Cannot create a chapter because this project has no volume.",
    cannotCreateActWithoutChapter: "Cannot create an act because this project has no chapter.",
    createVolumeFailed: "Failed to create volume",
    createChapterFailed: "Failed to create chapter",
    createActFailed: "Failed to create act",
    createSceneFailed: "Failed to create scene",
    renameVolumeFailed: "Failed to rename volume",
    renameChapterFailed: "Failed to rename chapter",
    renameActFailed: "Failed to rename act",
    deleteVolumeFailed: "Failed to delete volume",
    deleteChapterFailed: "Failed to delete chapter",
    deleteActFailed: "Failed to delete act",
    deleteSceneFailed: "Failed to delete scene",
    deleteProjectFailed: "Failed to permanently delete project",
    moveProjectToTrashFailed: "Failed to move project to trash",
    restoreProjectFailed: "Failed to restore project",
  },
  writeProgression: {
    title: "Codex progression",
    panelTitle: "Codex progressions",
    panelLabel: "Scene Codex progressions",
    panelEmpty: "No Codex progressions in this scene.",
    missingRecord: "Missing record",
    missingRecordBody: "The linked Codex progression could not be loaded.",
    chooseEntry: "Choose an entry",
    targetPrefix: "Add to:",
    fieldDescription: "Canon description",
    fieldFallback: "Detail",
    loading: "Loading",
    empty: "Empty",
    previewUnavailable: "Preview unavailable",
    laterChangesHidden: (count: number) => `${count} later change${count === 1 ? "" : "s"} hidden here.`,
    labels: {
      entry: "Entry",
      field: "Field",
      change: "Change",
      summary: "Summary",
      text: "Text",
      before: "Before",
      after: "After",
    },
    operations: {
      add: "Add before current text",
      replace: "Replace current text",
    },
    placeholders: {
      summary: "Short note for this change",
      text: "What becomes true from this point",
    },
    actions: {
      collapse: "Collapse",
      expand: "Expand",
      selectEntry: "Select",
    },
    aria: {
      addAfter: () => "Add Codex progression here",
      entry: (blockNumber: number) => `Codex progression entry ${blockNumber}`,
      field: (blockNumber: number) => `Codex progression field ${blockNumber}`,
      move: "Move Codex progression",
      operation: (blockNumber: number) => `Codex progression operation ${blockNumber}`,
      preview: (blockNumber: number) => `Codex progression preview ${blockNumber}`,
      summary: (blockNumber: number) => `Codex progression summary ${blockNumber}`,
      text: (blockNumber: number) => `Codex progression text ${blockNumber}`,
      selectedEntry: "Codex progression entry",
      selectedField: "Codex progression field",
      selectedOperation: "Codex progression operation",
      panelPreview: "Codex progression panel preview",
      selectedPreview: "Codex progression preview",
      selectedSummary: "Codex progression summary",
      selectedText: "Codex progression text",
      progressionList: "Codex progression list",
    },
    errors: {
      addFailed: "Failed to add Codex progression.",
      saveFailed: "Failed to save Codex progression.",
      deleteFailed: "Failed to delete Codex progression.",
      missingEntry: "Create a Codex entry before adding a Codex progression.",
      notLoaded: "The Codex progression record is not loaded.",
    },
  },
  writeEditor: {
    aria: {
      codexMentions: "Scene Codex mentions",
      content: "Scene content",
      editor: "Manuscript editor",
      toolbar: "Editor tools",
    },
    placeholders: {
      scene: "Continue the scene...",
    },
    tools: {
      addParagraph: "Add paragraph",
      deleteCurrent: "Delete current item",
      storyChange: "Codex progression",
    },
  },
  navigation: {
    notConnected: "Not connected",
    searchLabel: "Search unavailable",
    searchPlaceholder: "Search is not connected in this recovery slice",
  },
  review: {
    title: "Review Inbox",
    subtitle: "Interface retained while the review workflow is rebuilt.",
    status: "Not connected",
    filters: ["All", "Prose", "Continuity", "Facts"],
    queueTitle: "Queue",
    queueKicker: "No backend workflow",
    queueEmptyTitle: "No review workflow",
    queueEmptyBody: "Candidates and continuity items are not connected in this slice.",
    decisionTitle: "Decision",
    decisionKicker: "Unavailable",
    decisionEmptyTitle: "Review will be rebuilt",
    decisionEmptyBody: "This page stays visible, but it does not read or apply review items yet.",
    evidenceTitle: "Evidence",
    evidenceKicker: "Unavailable",
    evidenceBody: "Evidence panels return with the new Review workflow.",
    impactTitle: "Impact",
    impactKicker: "Unavailable",
    impactBody: "Batch impact previews are not connected.",
  },
  workshop: {
    title: "Workshop",
    subtitle: "Interface retained while Workshop is rebuilt.",
    status: "Not connected",
    newSession: "New Session",
    sessionsTitle: "Sessions",
    sessionsKicker: "No backend workflow",
    sessionsEmptyTitle: "No sessions",
    sessionsEmptyBody: "Persistent conversations are not connected in this slice.",
    conversationEmptyTitle: "Workshop will be rebuilt",
    conversationEmptyBody: "The page stays visible, but assistant sessions do not run yet.",
    inputPlaceholder: "Workshop is not connected",
    send: "Send",
    basketTitle: "Context Basket",
    basketKicker: "Unavailable",
    insert: "Insert",
    basketEmptyTitle: "No context basket",
    basketEmptyBody: "Scene and Codex context selection returns with the new Workshop workflow.",
  },
} as const;
