export const uiText = {
  actions: {
    add: "Add",
    cancel: "Cancel",
    delete: "Delete",
    save: "Save",
  },
  hierarchy: {
    volume: "Volume",
    chapter: "Chapter",
    act: "Act",
    scene: "Scene",
  },
  library: {
    deleteNameLabel: "Type the project name to permanently delete it",
    deletePermanently: "Delete permanently",
    deleteProjectCopy: (title: string) => `This permanently deletes "${title}" from disk. This cannot be undone.`,
    deleteProjectTitle: "Permanently delete project?",
    firstVolume: "First volume",
    moveToTrash: "Move to Trash",
    open: "Open",
    opening: "Opening",
    projectLibrary: "Project Library",
    restore: "Restore",
    trash: "Trash",
    trashEmpty: "Trash is empty.",
    volumes: "volumes",
  },
  structure: {
    title: "Structure",
    createItem: "Create structure item",
    confirmDeletion: "Confirm structure deletion",
    deleteSelected: (label: string) => `Delete selected ${label}?`,
    doubleClickToRename: "Double-click to rename",
    emptyScene: "No scene",
  },
  errors: {
    cannotCreateChapterWithoutVolume: "Cannot create a chapter because this project has no volume.",
    cannotCreateActWithoutChapter: "Cannot create an act because this project has no chapter.",
    createVolumeFailed: "Failed to create volume",
    createChapterFailed: "Failed to create chapter",
    createActFailed: "Failed to create act",
    createSceneFailed: "Failed to create scene",
    renameVolumeFailed: "Failed to rename volume",
    renameChapterFailed: "Failed to rename chapter",
    renameActFailed: "Failed to rename act",
    deleteVolumeFailed: "Failed to delete volume",
    deleteChapterFailed: "Failed to delete chapter",
    deleteActFailed: "Failed to delete act",
    deleteSceneFailed: "Failed to delete scene",
    deleteProjectFailed: "Failed to permanently delete project",
    moveProjectToTrashFailed: "Failed to move project to trash",
    restoreProjectFailed: "Failed to restore project",
    saveSceneFailed: "Failed to save scene",
  },
  writeProgression: {
    title: "Codex progression",
    missingRecord: "Missing record",
    missingRecordBody: "The linked Codex progression could not be loaded.",
    fieldDescription: "Canon description",
    fieldFallback: "Detail",
    operations: {
      add: "Add before",
      replace: "Replace",
    },
    emptyCollapsed: "No text yet",
    placeholders: {
      summary: "Short note for this change",
      text: "What becomes true from this point",
    },
    actions: {
      cancelDelete: "Cancel",
      collapseShort: "Collapse",
      confirmDelete: "Confirm delete Codex progression",
      collapse: "Collapse Codex progression",
      delete: "Delete Codex progression",
      deleteShort: "Delete",
      expand: "Expand Codex progression",
      expandShort: "Expand",
      selectEntry: "Select",
    },
    confirmDeleteCopy: "Delete this Codex progression?",
    aria: {
      addAfter: () => "Add Codex progression here",
      entry: (blockNumber: number) => `Codex progression entry ${blockNumber}`,
      field: (blockNumber: number) => `Codex progression field ${blockNumber}`,
      move: "Move Codex progression",
      operation: (blockNumber: number) => `Codex progression operation ${blockNumber}`,
      summary: (blockNumber: number) => `Codex progression summary ${blockNumber}`,
      text: (blockNumber: number) => `Codex progression text ${blockNumber}`,
      selectedEntry: "Codex progression entry",
      selectedField: "Codex progression field",
      selectedOperation: "Codex progression operation",
      selectedSummary: "Codex progression summary",
      selectedText: "Codex progression text",
    },
    errors: {
      addFailed: "Failed to add Codex progression.",
      saveFailed: "Failed to save Codex progression.",
      deleteFailed: "Failed to delete Codex progression.",
      missingEntry: "Create a Codex entry before adding a Codex progression.",
      notLoaded: "The Codex progression record is not loaded.",
    },
  },
  writeEditor: {
    aria: {
      codexMentions: "Scene Codex mentions",
      content: "Scene content",
      codexDescriptionPreview: (name: string) => `${name} canon description`,
      editor: "Manuscript editor",
      sceneTitle: "Scene title",
      toolbar: "Editor tools",
    },
    empty: {
      noDescription: "No description",
      noSceneBody: "Select a scene to begin writing.",
      noSceneTitle: "No scene open",
    },
    focus: {
      enter: "Focus",
      exit: "Exit Focus",
    },
    loadingCodex: "Loading codex",
    placeholders: {
      scene: "Continue the scene...",
    },
    sceneBrief: {
      cast: "Cast",
      continuity: "Continuity",
      goal: "Goal",
      hidePanel: "Hide panel",
      linkedCharacters: (count: number) => `${count} linked characters.`,
      noContinuity: "No continuity note yet.",
      noGoal: "No scene goal yet.",
      subtitle: "Visible while writing",
      title: "Scene Brief",
    },
    untitledScene: "Untitled Scene",
    tools: {
      insertMenu: "Insert",
      storyChange: "Codex progression",
    },
  },
  navigation: {
    notConnected: "Not connected",
    searchLabel: "Search unavailable",
    searchPlaceholder: "Search is not connected in this recovery slice",
  },
  review: {
    title: "Review Inbox",
    subtitle: "Interface retained while the review workflow is rebuilt.",
    status: "Not connected",
    filters: ["All", "Prose", "Continuity", "Facts"],
    queueTitle: "Queue",
    queueKicker: "No backend workflow",
    queueEmptyTitle: "No review workflow",
    queueEmptyBody: "Candidates and continuity items are not connected in this slice.",
    decisionTitle: "Decision",
    decisionKicker: "Unavailable",
    decisionEmptyTitle: "Review will be rebuilt",
    decisionEmptyBody: "This page stays visible, but it does not read or apply review items yet.",
    evidenceTitle: "Evidence",
    evidenceKicker: "Unavailable",
    evidenceBody: "Evidence panels return with the new Review workflow.",
    impactTitle: "Impact",
    impactKicker: "Unavailable",
    impactBody: "Batch impact previews are not connected.",
  },
  workshop: {
    title: "Workshop",
    subtitle: "Interface retained while Workshop is rebuilt.",
    status: "Not connected",
    newSession: "New Session",
    sessionsTitle: "Sessions",
    sessionsKicker: "No backend workflow",
    sessionsEmptyTitle: "No sessions",
    sessionsEmptyBody: "Persistent conversations are not connected in this slice.",
    conversationEmptyTitle: "Workshop will be rebuilt",
    conversationEmptyBody: "The page stays visible, but assistant sessions do not run yet.",
    inputPlaceholder: "Workshop is not connected",
    send: "Send",
    basketTitle: "Context Basket",
    basketKicker: "Unavailable",
    insert: "Insert",
    basketEmptyTitle: "No context basket",
    basketEmptyBody: "Scene and Codex context selection returns with the new Workshop workflow.",
  },
} as const;
